-- AlterTable
ALTER TABLE "Alert" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "resolvedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AnsiCategory" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Asset" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "setupOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AssetAlertCriterion" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AssetQuestion" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AssetQuestionResponse" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "startedOn" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "CompletedInspectionRoutePoint" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Consumable" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "expiresOn" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "ConsumableQuestionConfig" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Inspection" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "InspectionRoute" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "InspectionRoutePoint" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "InspectionSession" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Manufacturer" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Person" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "ProductCategory" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "ProductRequest" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "ProductRequestApproval" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "ProductRequestItem" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "SettingsBlock" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Site" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Tag" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "VaultOwnership" ALTER COLUMN "createdOn" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "modifiedOn" SET DATA TYPE TIMESTAMPTZ;
